### ISSUE TITLE
main file missing from npm

### ISSUE THREAD

**Issue by bernharduw** [hoytech/update-immutable#2]
Version 1.1.0 can't be installed correctly from npm: The dist/update.js file is missing.

![image](https://cloud.githubusercontent.com/assets/740978/25586312/12663988-2e9f-11e7-9343-48862c17b7e1.png)

**Comment by hoytech** [comment]
Ack, sorry about that. Still learning how the npm packaging stuff works. Can you please check now? I've uploaded 1.1.1 which seems to have the compiled version included.

**Comment by bernharduw** [comment]
Yes, looks good now! Thanks a lot for the quick fix!

![image](https://cloud.githubusercontent.com/assets/740978/25588197/9ec99778-2ea7-11e7-95c6-ca3845a642e5.png)
