### ISSUE TITLE
$set shallow equality doesn't work

### ISSUE THREAD

**Issue by GeKorm** [hoytech/update-immutable#3]
When I `$set` a property to the same value, the object isn't equal using triple equals. This isn't consistent with immutability-helper. See the example below:

https://www.webpackbin.com/bins/-KkVqR9VwotV8NAfoVbu

**Comment by hoytech** [comment]
Thanks for the report. Yes, I'm aware of this issue (see the "Todo" section of the README.md).

I'll probably get around to implementing it in the nearish future. Pull requests welcome of course. :)

**Comment by hoytech** [comment]
Thanks to @GeKorm's patch in PR #4, this feature will be implemented in version 1.2.0.
